apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pit
spec:
  minReplicas: 2
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60  # mais conservador em produção